### ISSUE TITLE
what kind of model is used here  trainning the emotion-recognition model

### ISSUE THREAD

**Issue by TheLostIn** [PINTO0309/OpenVINO-EmotionRecognition#5]
Hello,Mr Pinto,do you know what kind of model is used here for trainning the emotion-recognition model

**Comment by PINTO0309** [comment]
Please see the detailed description of the model below.

**https://github.com/opencv/open_model_zoo/blob/master/models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md**

**https://github.com/opencv/open_model_zoo/blob/master/models/intel/face-detection-retail-0004/description/face-detection-retail-0004.md**
